# Generated by Django 5.0 on 2024-08-30 14:04

import colorfield.fields
import django.core.serializers.json
import django.db.models.deletion
import school.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('uuid', models.CharField(default='41d27b', max_length=6)),
                ('address', models.CharField(max_length=255)),
                ('primary_color', colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=10, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#808080', image_field=None, max_length=10, samples=None)),
                ('premium', models.BooleanField(default=False)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(default='sample_logo.png', upload_to='logos/')),
                ('banner_video', models.FileField(blank=True, help_text='Upload a promotional video for the school.', null=True, upload_to='banner_videos/')),
                ('info', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, help_text='Upload a promotional video for the school.', null=True, upload_to='videos/')),
                ('video_thumbnail', models.ImageField(blank=True, default='sample_logo.png', null=True, upload_to='video_thumbnail/')),
                ('top_bar_notifications', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of notifications for the top bar')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PTA Announcement', max_length=100)),
                ('summary', models.TextField(default='This Quarter PTA will be held on the 2nd Saturday')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='sample-news.png', upload_to='news/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(default='Short text about the school.')),
                ('links', models.JSONField(default=school.models_utils.default_json_data_links)),
                ('social_media', models.JSONField(default=school.models_utils.default_json_data_social_media)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='sample_banner.jpeg', upload_to='banners/')),
                ('headline', models.CharField(default='Welcome To ABC School', max_length=200)),
                ('subtext', models.TextField(default='A place of excellence in learning and teaching')),
                ('cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_link', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=100)),
                ('content', models.TextField(default='Detailed text about the school')),
                ('image', models.ImageField(default='about-section-sample.png', upload_to='about-section/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(default='This school has been a fantastic experience for my child.')),
                ('author', models.CharField(default='Mr Abc Xyz', max_length=100)),
                ('relation', models.CharField(default='Father Of Ijk', max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
