# Generated by Django 5.0 on 2023-12-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='cta_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='navigationmenu',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='56e1e', max_length=5),
        ),
    ]
