# Generated by Django 5.0 on 2023-12-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_banner_cta_link_alter_navigationmenu_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='8a544', max_length=5),
        ),
    ]
