# Generated by Django 5.0 on 2024-09-01 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_latitude_school_longitude_alter_school_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or provide a URL to a promotional video for the school.', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='453a04', max_length=6),
        ),
    ]
