# Generated by Django 5.0 on 2024-01-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(default='about-section/about-section-sample.png', upload_to='about-section/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='banners/sample_banner.jpeg', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(default='news/sample-news.png', upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='logos/sample_logo.png', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='331f9', max_length=5),
        ),
    ]
