# Generated by Django 5.0 on 2024-01-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_aboutsection_image_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(default='about-section-sample.png', upload_to='about-section/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='sample_banner.jpeg', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(default='sample-news.png', upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='sample_logo.png', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='9b94f', max_length=5),
        ),
    ]
