# Generated by Django 5.0 on 2024-01-14 11:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_aboutsection_image_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=10, samples=None),
        ),
        migrations.AlterField(
            model_name='school',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#808080', image_field=None, max_length=10, samples=None),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='abbf4', max_length=5),
        ),
    ]
