# Generated by Django 5.0 on 2024-09-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_course_name_school_date_alter_school_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='date',
        ),
        migrations.AddField(
            model_name='school',
            name='course_registration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='c74cd5', max_length=6),
        ),
    ]
