# Generated by Django 5.0 on 2024-03-07 09:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_school_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='top_bar_notifications',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of notifications for the top bar'),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='01d5b', max_length=5),
        ),
    ]
