# Generated by Django 5.0 on 2024-04-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_school_top_bar_notifications_alter_school_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='d715d9', max_length=6),
        ),
    ]
