# Generated by Django 5.0 on 2024-04-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_school_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='1b7a07', max_length=6),
        ),
    ]
