# Generated by Django 5.0 on 2024-09-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_school_top_bar_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='video',
            field=models.FileField(blank=True, default='course-video.mp4', help_text='Upload a promotional video for the school.', null=True, upload_to='videos/'),
        ),
    ]
