# Generated by Django 5.0 on 2024-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_contactformentry_alter_school_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='055cfd', max_length=6),
        ),
    ]
