# Generated by Django 5.0 on 2024-09-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_school_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='banner_video',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_video',
            field=models.FileField(blank=True, default='course-video.mp4', help_text='Upload a promotional video for the school.', null=True, upload_to='banner_videos/'),
        ),
    ]
