# Generated by Django 5.0 on 2024-09-08 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_school_banner_video_banner_banner_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='course_name',
            new_name='upcoming_registration',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='course_registration_end_date',
            new_name='upcoming_registration_end_date',
        ),
        migrations.AlterField(
            model_name='school',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a promotional video for the school.', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='video_thumbnail',
            field=models.ImageField(blank=True, default='main-thumb.png', null=True, upload_to='video_thumbnail/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='video_url',
            field=models.URLField(blank=True, default='https://youtu.be/szjVXpnabmI', help_text='Or provide a URL to a promotional video for the school.', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
